substitutions:
  _NEXT_PUBLIC_FIREBASE_API_KEY: ""
  _NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN: ""
  _NEXT_PUBLIC_FIREBASE_PROJECT_ID: ""
  _NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET: ""
  _NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID: ""
  _NEXT_PUBLIC_FIREBASE_APP_ID: ""
  _NEXT_PUBLIC_TUS_ENDPOINT: ""
  _IMAGE_NAME: "europe-central2-docker.pkg.dev/$PROJECT_ID/chmura-blokserwis-nextjs/app"

steps:

  - name: 'gcr.io/cloud-builders/docker'
    id: Pull-Latest-For-Cache
    entrypoint: 'bash'
    args:
      - '-c'
      - 'docker pull ${_IMAGE_NAME}:latest || exit 0'
  - name: 'gcr.io/cloud-builders/docker'
    id: Build
    args:
      - 'build'
      - '-t'
      - '${_IMAGE_NAME}:$SHORT_SHA'
      - '--cache-from'
      - '${_IMAGE_NAME}:latest'
      - '-f'
      - 'frontend/Dockerfile'
      - '--build-arg'
      - 'NEXT_PUBLIC_FIREBASE_API_KEY=${_NEXT_PUBLIC_FIREBASE_API_KEY}'
      - '--build-arg'
      - 'NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN=${_NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN}'
      - '--build-arg'
      - 'NEXT_PUBLIC_FIREBASE_PROJECT_ID=${_NEXT_PUBLIC_FIREBASE_PROJECT_ID}'
      - '--build-arg'
      - 'NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET=${_NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET}'
      - '--build-arg'
      - 'NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID=${_NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID}'
      - '--build-arg'
      - 'NEXT_PUBLIC_FIREBASE_APP_ID=${_NEXT_PUBLIC_FIREBASE_APP_ID}'
      - '--build-arg'
      - 'NEXT_PUBLIC_TUS_ENDPOINT=${_NEXT_PUBLIC_TUS_ENDPOINT}'
      - 'frontend'

  # KROK 3: Dodaj tag "latest" do nowo zbudowanego obrazu.
  # Ten tag będzie użyty przez następną kompilację jako źródło cache.
  - name: 'gcr.io/cloud-builders/docker'
    id: Tag-As-Latest
    args: ['tag', '${_IMAGE_NAME}:$SHORT_SHA', '${_IMAGE_NAME}:latest']

  # KROK 4: Wypchnij obraz z unikalnym tagiem $SHORT_SHA.
  # Ten obraz zostanie użyty do wdrożenia na Cloud Run.
  - name: 'gcr.io/cloud-builders/docker'
    id: Push-SHA-Tag
    args: ['push', '${_IMAGE_NAME}:$SHORT_SHA']

  # KROK 5: Wypchnij obraz z tagiem "latest".
  # To aktualizuje wersję w repozytorium, która posłuży jako cache dla kolejnego buildu.
  - name: 'gcr.io/cloud-builders/docker'
    id: Push-Latest-Tag
    args: ['push', '${_IMAGE_NAME}:latest']

  # KROK 6: Wdróż na Cloud Run, używając obrazu z unikalnym tagiem SHA.
  # Użycie `waitFor` gwarantuje, że ten krok uruchomi się dopiero po pomyślnym wypchnięciu obrazu.
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: Deploy-To-Cloud-Run
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'chmura-blokserwis-app'
      - '--image'
      - '${_IMAGE_NAME}:$SHORT_SHA'
      - '--region'
      - 'europe-central2'
      - '--platform'
      - 'managed'
    waitFor:
      - 'Push-SHA-Tag'

options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8'

images:
  - '${_IMAGE_NAME}:$SHORT_SHA'
  - '${_IMAGE_NAME}:latest'