substitutions:
  _NEXT_PUBLIC_FIREBASE_API_KEY: ""
  _NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN: ""
  _NEXT_PUBLIC_FIREBASE_PROJECT_ID: ""
  _NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET: ""
  _NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID: ""
  _NEXT_PUBLIC_FIREBASE_APP_ID: ""
  _R2_PUBLIC_HOSTNAME: ""

steps:
  # KROK 0: Repair git shallow clone 
  - name: 'gcr.io/cloud-builders/git'
    id: Unshallow-Git
    args: ['fetch', '--unshallow']

  # KROK 0.1: Checkout main explicitly
  - name: 'gcr.io/cloud-builders/git'
    id: Checkout-Main
    args: ['checkout', 'main']

  # KROK 0.5: Semantic Release
  - name: 'node:20'
    id: Semantic-Release
    entrypoint: 'npx'
    args:
      - '-p'
      - 'semantic-release'
      - '-p'
      - '@semantic-release/changelog'
      - '-p'
      - '@semantic-release/git'
      - 'semantic-release'
    secretEnv: ['GITHUB_TOKEN']
    env:
      - 'CI=true'

  # KROK 1: Pull cache
  - name: 'gcr.io/cloud-builders/docker'
    id: Pull-Latest-For-Cache
    entrypoint: 'bash'
    args:
      - '-c'
      - 'docker pull europe-central2-docker.pkg.dev/$PROJECT_ID/chmura-blokserwis-nextjs/app:latest || exit 0'

  # KROK 2: Build
  - name: 'gcr.io/cloud-builders/docker'
    id: Build
    args:
      - 'build'
      - '-t'
      - 'europe-central2-docker.pkg.dev/$PROJECT_ID/chmura-blokserwis-nextjs/app:$SHORT_SHA'
      - '--cache-from'
      - 'europe-central2-docker.pkg.dev/$PROJECT_ID/chmura-blokserwis-nextjs/app:latest'
      - '--build-arg'
      - 'NEXT_PUBLIC_FIREBASE_API_KEY=${_NEXT_PUBLIC_FIREBASE_API_KEY}'
      - '--build-arg'
      - 'NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN=${_NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN}'
      - '--build-arg'
      - 'NEXT_PUBLIC_FIREBASE_PROJECT_ID=${_NEXT_PUBLIC_FIREBASE_PROJECT_ID}'
      - '--build-arg'
      - 'NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET=${_NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET}'
      - '--build-arg'
      - 'NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID=${_NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID}'
      - '--build-arg'
      - 'NEXT_PUBLIC_FIREBASE_APP_ID=${_NEXT_PUBLIC_FIREBASE_APP_ID}'
      - '--build-arg'
      - 'R2_PUBLIC_HOSTNAME=${_R2_PUBLIC_HOSTNAME}'
      - '.'
    secretEnv: ['GITHUB_TOKEN']

  # KROK 3: Tag Latest
  - name: 'gcr.io/cloud-builders/docker'
    id: Tag-As-Latest
    args:
      - 'tag'
      - 'europe-central2-docker.pkg.dev/$PROJECT_ID/chmura-blokserwis-nextjs/app:$SHORT_SHA'
      - 'europe-central2-docker.pkg.dev/$PROJECT_ID/chmura-blokserwis-nextjs/app:latest'

  # KROK 4: Push SHA
  - name: 'gcr.io/cloud-builders/docker'
    id: Push-SHA-Tag
    args: ['push', 'europe-central2-docker.pkg.dev/$PROJECT_ID/chmura-blokserwis-nextjs/app:$SHORT_SHA']

  # KROK 5: Push Latest
  - name: 'gcr.io/cloud-builders/docker'
    id: Push-Latest-Tag
    args: ['push', 'europe-central2-docker.pkg.dev/$PROJECT_ID/chmura-blokserwis-nextjs/app:latest']

  # KROK 6: Deploy Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: Deploy-To-Cloud-Run
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'chmura-blokserwis-app'
      - '--image'
      - 'europe-central2-docker.pkg.dev/$PROJECT_ID/chmura-blokserwis-nextjs/app:$SHORT_SHA'
      - '--region'
      - 'europe-central2'
      - '--platform'
      - 'managed'
    waitFor:
      - 'Push-SHA-Tag'

options:
  logging: CLOUD_LOGGING_ONLY

images:
  - 'europe-central2-docker.pkg.dev/$PROJECT_ID/chmura-blokserwis-nextjs/app:$SHORT_SHA'
  - 'europe-central2-docker.pkg.dev/$PROJECT_ID/chmura-blokserwis-nextjs/app:latest'

# NOWA SEKCJA: Mapowanie Secret Managera na zmienne środowiskowe
availableSecrets:
  secretManager:
  - versionName: projects/$PROJECT_ID/secrets/github_token/versions/latest
    env: 'GITHUB_TOKEN'