substitutions:
  _NEXT_PUBLIC_FIREBASE_API_KEY: ""
  _NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN: ""
  _NEXT_PUBLIC_FIREBASE_PROJECT_ID: ""
  _NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET: ""
  _NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID: ""
  _NEXT_PUBLIC_FIREBASE_APP_ID: ""

steps:
  # Build Frontend (Next.js) image from ./frontend
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'europe-central2-docker.pkg.dev/$PROJECT_ID/chmura-blokserwis-nextjs/app:$SHORT_SHA'
      - '-f'
      - 'frontend/Dockerfile'
      - '--build-arg'
      - 'NEXT_PUBLIC_FIREBASE_API_KEY=${_NEXT_PUBLIC_FIREBASE_API_KEY}'
      - '--build-arg'
      - 'NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN=${_NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN}'
      - '--build-arg'
      - 'NEXT_PUBLIC_FIREBASE_PROJECT_ID=${_NEXT_PUBLIC_FIREBASE_PROJECT_ID}'
      - '--build-arg'
      - 'NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET=${_NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET}'
      - '--build-arg'
      - 'NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID=${_NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID}'
      - '--build-arg'
      - 'NEXT_PUBLIC_FIREBASE_APP_ID=${_NEXT_PUBLIC_FIREBASE_APP_ID}'
      - 'frontend'

  # Push Frontend image
  - name: 'gcr.io/cloud-builders/docker'
    id: Push Frontend
    args:
      [
        'push',
        'europe-central2-docker.pkg.dev/$PROJECT_ID/chmura-blokserwis-nextjs/app:$SHORT_SHA'
      ]

  # Build Backend image from ./backend
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'europe-central2-docker.pkg.dev/$PROJECT_ID/chmura-blokserwis-nextjs/api:$SHORT_SHA'
      - '-f'
      - 'backend/Dockerfile'
      - 'backend'

  # Push Backend image
  - name: 'gcr.io/cloud-builders/docker'
    id: Push Backend
    args:
      [
        'push',
        'europe-central2-docker.pkg.dev/$PROJECT_ID/chmura-blokserwis-nextjs/api:$SHORT_SHA'
      ]

  # Deploy Frontend to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'chmura-blokserwis-app'
      - '--image'
      - 'europe-central2-docker.pkg.dev/$PROJECT_ID/chmura-blokserwis-nextjs/app:$SHORT_SHA'
      - '--region'
      - 'europe-central2'
      - '--platform'
      - 'managed'

  # Deploy Backend to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'chmura-blokserwis-backend'
      - '--image'
      - 'europe-central2-docker.pkg.dev/$PROJECT_ID/chmura-blokserwis-nextjs/api:$SHORT_SHA'
      - '--region'
      - 'europe-central2'
      - '--platform'
      - 'managed'

options:
  logging: CLOUD_LOGGING_ONLY

images:
  - 'europe-central2-docker.pkg.dev/$PROJECT_ID/chmura-blokserwis-nextjs/app:$SHORT_SHA'
  - 'europe-central2-docker.pkg.dev/$PROJECT_ID/chmura-blokserwis-nextjs/api:$SHORT_SHA'


